### ISSUE TITLE
No global resource cache

### ISSUE THREAD

**Issue by chrismbeckett** [PolymerElements/app-localize-behavior#23]
The documentation states that ``All of these elements share a common localization cache, so you only need to load translations once.``, but I am having to set the language and load resources locally in every element.

**Comment by notwaldorf** [comment]
Yeah, I think that I explained that poorly. You still have to load the resources in any element that implements the behaviour, but if you load the same resource file, then the cached one will be used and you won't make an extra ajax request. 

You have to specify the language and the resources in every element because some elements might use different resource files, so it's not necessarily obvious which file applies to which element.

Hope this helps! If you want to send a PR to fix the wording of the docs, that would be awesome! If not, I'll get to it next week :)

**Comment by chrismbeckett** [comment]
Thank you for the update.
