### ISSUE TITLE
detection

### ISSUE THREAD

**Issue by ghost** [PolymerElements/app-localize-behavior#39]
How to detect user language in the browser using either:
- cookie
- localStorage
- navigator
- querystring
- htmlTag

This should be part of the Localize system i feel. I cant see this currently

**Comment by dgabrielli76** [comment]
Personally I use `navigator.language` to detect it.
I have created my own behavior to prevent duplicate code in every element that need to use localization.
I also agree that could be part of the Localize system.

**Comment by gedw99** [comment]
@dgabrielli76 
Could i have a look at the behaviour you wrote to get around this ?
Is the code in a PR push back to this repo ? I cant see one form you waiting.

**Comment by dgabrielli76** [comment]
What I have done in my behavior is to override the `language` property of the AppLocalizeBehavior: 
```
    properties: {
      /* Overriden fromAppLocalizeBehavior */
      language: {
        value: function() {
          // Checks navigator language and keep just the language
          // identification code of the country
          var navigatorLanguage = navigator.language.split('-')[0];
          if (navigatorLanguage === 'fr') {
            return navigatorLanguage;
          } else {
            return 'en';
          }
        },
        type: String
      }
    }
```
The only thing to do is to import this behavior in each element that needs localize system.
In this example I just do a test for the `fr` value because I only have two dictionaries (French and English) but this example could be adapt for other dictionaries.

I hope it could help you!

**Comment by gedw99** [comment]
@dgabrielli76 thanks.

Ok makes sense. 

I think this might be an elegant solution:

1. Make a "app-localize-detect" element, that then sets state in the local storage. This would be set in the root of the component hierarchy. In that we can implement as many as we want in terms of detection mechanisms.  In terms of state, it wil set a name / value pair in the local state.

2. Modify "app-localise-behaviour" element to look for the name / value state and respond accordingly. 

I am pretty new to Polymer, and dont know if this is the "right" way..
? @notwaldorf

Any takers ?

**Comment by dgabrielli76** [comment]
Pleased if it helped you 😄

**Comment by JosefJezek** [comment]
Check out this behavior...
https://github.com/StartPolymer/progressive-web-app-template/blob/master/src/app-behaviors/app-localize-behavior.html

**Comment by notwaldorf** [comment]
The answer in https://github.com/PolymerElements/app-localize-behavior/issues/39#issuecomment-235377061 looks simple enough that makes me think this is a thing that lives in your application, rather than in the behaviour itself. I'm also worried that automatically detecting the language isn't always great -- what if my language is a value the app doesn't support?

I'll tentatively close this issue and point to @dgabrielli76's answer as a thing you should do, and see how this goes.

**Comment by dgabrielli76** [comment]
I agree with you @notwaldorf that this is a thing that lives in the application, rather than in the behaviour itself.

To answer your question if the language detected is a value the app doesn't support, for my application the english language is set by default.
If somebody want more information I will be pleased to help!
